# Just some constants that are used
STEAM = "Steam"
PS4 = "PS4"
XBOX1 = "XboxOne"

ALL_PLATFORMS = {STEAM, PS4, XBOX1}

STEAM_ID = 1
PS4_ID = 2
XBOX1_ID = 3

ALL_IDS = {STEAM_ID, PS4_ID, XBOX1_ID}
ID_PLATFORM_LUT = {STEAM_ID: STEAM, PS4_ID: PS4, XBOX1_ID: XBOX1}
PLATFORM_ID_LUT = {STEAM: STEAM_ID, PS4: PS4_ID, XBOX1: XBOX1_ID}
